version: '3'
services:
  todo-app-frontend:
    build: todo-app-frontend
    image: frontend:latest
    # environment:
    #   PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - todo-app-backend
  todo-app-backend:
    build: todo-app-backend
    image: backend:latest
    # environment:
    #   PORT: 3001
    expose:
      - 3001
    ports:
      - "3001:3001"
