apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: todo-app-backend
  name: todo-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todo-app-backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: todo-app-backend
    spec:
      containers:
        - image: backend:latest
          name: todo-app-backend
          ports:
            - containerPort: 3001
          resources: {}
      restartPolicy: Always
status: {}
